config/routes.rb
Rails.application.routes.draw do

  default_url_options :host => "bhargav.thummar@bacancytechnology.com"
  
  root to: 'books#index'
  devise_for :users 

  get '/users/index' => 'users#index'
  delete 'users/:id' => 'users#destroy', :method => :delete, :as => :destroy_user

  get '/books/index2' => 'books#index2'
  resources :books do
    resources :comments
  end

  resources :categories
 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many :book_sellers, dependent: :destroy
  has_one_attached :image 

  scope :searching,->(s){Book.joins(:category).where("books.book_name LIKE ? OR books.book_author LIKE ? OR books.isbn LIKE ? OR categories.category_name LIKE ? ","%#{s}%","%#{s}%","%#{s}%","%#{s}%") }
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show,:index,:index2]
   
  # GET /books
  # GET /books.json

  def index
    # @book = Book.ransack(params[:q])
    # @books_result = @book.result(distinct: true) 
       
    if params[:query].present?
    
    @books_result = Book.searching(params[:query])
    else
    @books_result = Book.all
    end

  end

  def index2
  
    # @book = Book.ransack(params[:q])
    # @s = BookSeller
    # @s = @s.where('seller_id = ?', current_user.id)
    # @s = @s.select('book_id')
    # @q = Book
    # @books_result = @book.result.where(id: [@s])

      @s = BookSeller
      @s = @s.where('seller_id = ?', current_user.id)
      @s = @s.select('book_id')
      @q = Book

      if params[:query].present?
      @books_result = Book.searching(params[:query]).where(id: [@s])
      else
      @books_result = @q.where(id: [@s])
      end 
   end

  # GET /books/1
  # GET /books/1.json 
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

  
    respond_to do |format|
      if @book.save
        @book_seller = BookSeller.new(seller_id: current_user.id, book_id: @book.id)
        # @book_seller.seller_id = current_user.id
        # @book_seller.book_id = @book.id
        @book_seller.save
        format.html { redirect_to book_path(@book ,@book_seller), notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_path(@book, @book_seller), notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
      @book_seller = BookSeller.find_by(book: @book, seller: current_user)
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:book_name, :book_description, :book_author, :book_price, :book_qty, :isbn, :category_id, :image)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :book_name %>
    <%= form.text_field :book_name %>
  </div>

  <div class="field">
    <%= form.label :book_description %>
    <%= form.text_area :book_description %>
  </div>

  <div class="field">
    <%= form.label :book_author %>
    <%= form.text_field :book_author %>
  </div>

  <div class="field">
  <%= form.label :isbn %>
  <%= form.text_field :isbn %>
</div>

  <div class="field">
    <%= form.label :book_price %>
    <%= form.text_field :book_price %>
  </div>

  <div class="field">
    <%= form.label :book_qty %>
    <%= form.number_field :book_qty %>
  </div>

  <div class="field">
  <%= form.label :image %>
  <%= form.file_field :image %>
</div>

  <div class="field">
    <%= form.collection_select :category_id, Category.all,:id,:category_name, include_blank: false %>
  </div>

<br>
  <% if current_user && current_user.admin %>
    <%= link_to 'Add new category',categories_path %> 
    <% end %>
<br>
<br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Books</h1>

<%= form_tag("/", method: "get", remote: false) do %>
  <%= text_field_tag :query, params[:query] %>
  <%= submit_tag "search" %>
  <% end %>
<br>
<table border="2">
  <thead>
    <tr>
      <th>Book name</th>
      <th>Book description</th>
      <th>Book author</th>
      <th>ISBN</th>
      <th>Book price</th>
      <th>Book qty</th>
      <th>Category</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @books_result.each do |book| %>
      <tr>
        <td><%= book.book_name %></td>
        <td><%= book.book_description %></td>
        <td><%= book.book_author %></td>
        <td><%= book.isbn %></td>
        <td><%= book.book_price %></td>
        <td><%= book.book_qty %></td>
        <td><%= book.category.category_name %></td>
        <td><%= link_to 'Show', book %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Back','/' %> 
<% if current_user %>
| <%= link_to 'New Book', new_book_path %>
<% end %>

app/views/books/index2.html.erb
<h1>Your Uploads</h1>

<%= form_tag("/books/index2", method: "get", remote: false) do %>
  <%= text_field_tag :query, params[:query] %>
  <%= submit_tag "search" %>
  <% end %>
  <br>

<table border="2">
  <thead>
    <tr>
      <th>Book name</th>
      <th>Book description</th>
      <th>Book author</th>
      <th>ISBN</th>
      <th>Book price</th>
      <th>Book qty</th>
      <th>Category</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @books_result.each do |book| %>
      <tr>
        <td><%= book.book_name %></td>
        <td><%= book.book_description %></td>
        <td><%= book.book_author %></td>
        <td><%= book.isbn %></td>
        <td><%= book.book_price %></td>
        <td><%= book.book_qty %></td>
        <td><%= book.category.category_name %></td>
        <td><%= link_to 'Show', book %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Back','/books/index2' %> 
<% if current_user %>
| <%= link_to 'New Book', new_book_path %>
<% end %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
 <% if @book.image.present? %>
<div style="width:400px; hiegth:auto" >
<%= image_tag(@book.image, style:"width:100%") %>
</div>
<% else %>
<h3> Image is not uploaded </h3>
<% end %>

<p>
  <strong>Book name:</strong>
  <%= @book.book_name %>
</p>

<p>
  <strong>Book description:</strong>
  <%= @book.book_description %>
</p>

<p>
  <strong>Book author:</strong>
  <%= @book.book_author %>
</p>

<p>
  <strong>ISBN no:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Book price:</strong>
  <%= @book.book_price %>
</p>

<p>
  <strong>Book qty:</strong>
  <%= @book.book_qty %>
</p>

<p>
  <strong>Category:</strong>
  <%= @book.category.category_name %>
</p>

<hr>
<h2>Comments</h2>
 <%= render @book.comments %>
 <hr>

 <% if current_user %>
<h2> Add Comments here </h2>
<%= render 'comments/form' %>
<% else %>
<h3> Please Sign in for add comments </h3>
<% end %>

<br>

<% if @book_seller.present? %>
<% if current_user && (@book_seller.seller_id == current_user.id || current_user.admin) %>
<%= link_to 'Edit', edit_book_path(@book ,@book_seller) %> |
<% end %>
<% end %>

<% if current_user && current_user.admin %>
<%= link_to 'Destroy', @book, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %> 

<%= link_to 'Back', books_path %>